//#region  country
export const country = [
  { "id": "BKrv6cuhQfIKZt5D", "name": "Afghanistan", "code": "AF" },
  { "id": "88k1Oj520bZCLIMi", "name": "Åland Islands", "code": "AX" },
  { "id": "FGHHN-x1pR4j-VOb", "name": "Albania", "code": "AL" },
  { "id": "uFc_cdEpmDVOnGVc", "name": "Algeria", "code": "DZ" },
  { "id": "SxWarf-W7RjqzrIp", "name": "American Samoa", "code": "AS" },
  { "id": "mFzw8MwXuS37C5lv", "name": "Andorra", "code": "AD" },
  { "id": "g333qSEMMGebjQjx", "name": "Angola", "code": "AO" },
  { "id": "EvCNICRJ3I5v0ESY", "name": "Anguilla", "code": "AI" },
  { "id": "dsZlyahlsxGYVrNq", "name": "Antarctica", "code": "AQ" },
  { "id": "kPafIPTyYS6F9ysV", "name": "Antigua And Barbuda", "code": "AG" },
  { "id": "YUZbwyrs5mvpU8Br", "name": "Argentina", "code": "AR" },
  { "id": "FzetJCNNxnJtHH1U", "name": "Armenia", "code": "AM" },
  { "id": "GLlKzV2DHTMJtyyG", "name": "Aruba", "code": "AW" },
  { "id": "vr-_9KbU8KSY3IA2", "name": "Australia", "code": "AU" },
  { "id": "6tmuPYy8PWAEZfCu", "name": "Austria", "code": "AT" },
  { "id": "z66ukhQmiQtInXbG", "name": "Azerbaijan", "code": "AZ" },
  { "id": "pxvgfj7Q7gU55guK", "name": "Bahamas", "code": "BS" },
  { "id": "RJg-ifep0uPeWyFl", "name": "Bahrain", "code": "BH" },
  { "id": "SEGq6SC6NBQw4tP9", "name": "Bangladesh", "code": "BD" },
  { "id": "MIO1hTLWkgZH-pwt", "name": "Barbados", "code": "BB" },
  { "id": "599NHP0d6JJ3yzSS", "name": "Belarus", "code": "BY" },
  { "id": "hfraeBTPpwVppAB-", "name": "Belgium", "code": "BE" },
  { "id": "9BMPq9jKk1lQSl0Y", "name": "Belize", "code": "BZ" },
  { "id": "FmQ_x0UNPppQB42C", "name": "Benin", "code": "BJ" },
  { "id": "P0-DZNphFa3cdRd2", "name": "Bermuda", "code": "BM" },
  { "id": "lSjHIy1N7eIqXiSk", "name": "Bhutan", "code": "BT" },
  { "id": "lX4TBdNbv9_gm27h", "name": "Bolivia, Plurinational State Of", "code": "BO" },
  { "id": "Ni747VbCtQS0B7m-", "name": "Bonaire, Sint Eustatius And Saba", "code": "BQ" },
  { "id": "jaN66At1gdFSTaZe", "name": "Bosnia And Herzegovina", "code": "BA" },
  { "id": "xyywj-QKmm8IjYTg", "name": "Botswana", "code": "BW" },
  { "id": "zZ5eMLbupv8wCLV8", "name": "Bouvet Island", "code": "BV" },
  { "id": "05B2msDp0-wVBoFr", "name": "Brazil", "code": "BR" },
  { "id": "uStoaoTOobeorjKD", "name": "British Indian Ocean Territory", "code": "IO" },
  { "id": "p8reQL8mJM8x9y2-", "name": "Brunei Darussalam", "code": "BN" },
  { "id": "8wbDRUB3yH5riHKL", "name": "Bulgaria", "code": "BG" },
  { "id": "Et7KHbdu0IYu3951", "name": "Burkina Faso", "code": "BF" },
  { "id": "UcJ_Wmco3Gdl_vNP", "name": "Burundi", "code": "BI" },
  { "id": "CqmtHyZ5q5HasJQV", "name": "Cambodia", "code": "KH" },
  { "id": "xwJMQkplCwsvK5Ee", "name": "Cameroon", "code": "CM" },
  { "id": "DZe3L-Gxv0bQW7Ac", "name": "Canada", "code": "CA" },
  { "id": "s78N9ib-plAt7JyP", "name": "Cape Verde", "code": "CV" },
  { "id": "soWhYGwGaWHSNqEW", "name": "Cayman Islands", "code": "KY" },
  { "id": "eEuaGvI9dL0Ex614", "name": "Central African Republic", "code": "CF" },
  { "id": "k9z_6A77VCN21QAH", "name": "Chad", "code": "TD" },
  { "id": "1anzXDMfXg9HsQuX", "name": "Chile", "code": "CL" },
  { "id": "7mWIN7e1L1kZpyfr", "name": "China", "code": "CN" },
  { "id": "mDLcQcd1zk7Q2BqT", "name": "Christmas Island", "code": "CX" },
  { "id": "HXeK5TwysB7aQSmY", "name": "Cocos (keeling) Islands", "code": "CC" },
  { "id": "dxT82pq6ON4VOBKg", "name": "Colombia", "code": "CO" },
  { "id": "pE6QIdr34yW3Es0s", "name": "Comoros", "code": "KM" },
  { "id": "r3do76Qlo0CVInUB", "name": "Congo", "code": "CG" },
  { "id": "SmAqp1KLRDEgF6UK", "name": "Congo, The Democratic Republic Of The", "code": "CD" },
  { "id": "nv9NdfVFNU-ndJbu", "name": "Cook Islands", "code": "CK" },
  { "id": "UUe0sc75AJZ3sR0u", "name": "Costa Rica", "code": "CR" },
  { "id": "3pz1lyavZCvjgFKl", "name": "Côte D ivoire", "code": "CI" },
  { "id": "9CaZ4MCHbEe16NKE", "name": "Croatia", "code": "HR" },
  { "id": "6y1zev-oU5S7MhLJ", "name": "Cuba", "code": "CU" },
  { "id": "xEjfW3Q_Tu3tXclZ", "name": "Curaçao", "code": "CW" },
  { "id": "QXuymljeUtUZ6j4N", "name": "Cyprus", "code": "CY" },
  { "id": "TYvaCUK8MM6_hvb2", "name": "Czech Republic", "code": "CZ" },
  { "id": "CTTwDBHEAbUZ6iWp", "name": "Denmark", "code": "DK" },
  { "id": "AR4owPXk_1j024qe", "name": "Djibouti", "code": "DJ" },
  { "id": "YABSJf6DMAwJuSa3", "name": "Dominica", "code": "DM" },
  { "id": "5K__lkWMjSdy6vK6", "name": "Dominican Republic", "code": "DO" },
  { "id": "XtxARhuMhcY__BbQ", "name": "Ecuador", "code": "EC" },
  { "id": "uXJdB1GK9899-s7f", "name": "Egypt", "code": "EG" },
  { "id": "tKlND7SYmLp4XJYS", "name": "El Salvador", "code": "SV" },
  { "id": "kP6h8URYGbI6FsBc", "name": "Equatorial Guinea", "code": "GQ" },
  { "id": "7r8jvQfDN6kkHZBk", "name": "Eritrea", "code": "ER" },
  { "id": "fJxg_iYlNWHJL8F4", "name": "Estonia", "code": "EE" },
  { "id": "7wNCEGSEnONdlMjB", "name": "Ethiopia", "code": "ET" },
  { "id": "YED3nXzbRFTjvnh2", "name": "Falkland Islands (malvinas)", "code": "FK" },
  { "id": "wFK09DGGPVFKk1RO", "name": "Faroe Islands", "code": "FO" },
  { "id": "XcIbP_xjcHIvaRPL", "name": "Fiji", "code": "FJ" },
  { "id": "4nd6hdy_yisWnguB", "name": "Finland", "code": "FI" },
  { "id": "Ls4THWluL1nTdVAK", "name": "France", "code": "FR" },
  { "id": "UviZX-IjetEMWMHE", "name": "French Guiana", "code": "GF" },
  { "id": "uXhL1TQeh_fGiRpY", "name": "French Polynesia", "code": "PF" },
  { "id": "E_uuqbmaJDi2b0lv", "name": "French Southern Territories", "code": "TF" },
  { "id": "WTwlR-F_4UopElx6", "name": "Gabon", "code": "GA" },
  { "id": "C5LmGkqlym4hScUE", "name": "Gambia", "code": "GM" },
  { "id": "O36toO6tPKz-2wp4", "name": "Georgia", "code": "GE" },
  { "id": "9mCefy2_zNExNODJ", "name": "Germany", "code": "DE" },
  { "id": "xJL3RKRYo9kY5XVB", "name": "Ghana", "code": "GH" },
  { "id": "t7Da1B1BP2n86IKn", "name": "Gibraltar", "code": "GI" },
  { "id": "53KRrlVJ7NzepSL6", "name": "Greece", "code": "GR" },
  { "id": "98IZ_Z59QVKHXElR", "name": "Greenland", "code": "GL" },
  { "id": "JTNkgV_S-X356Fw1", "name": "Grenada", "code": "GD" },
  { "id": "W_QybZzATmo_Krvh", "name": "Guadeloupe", "code": "GP" },
  { "id": "N9HQP3eoWXm6Gx91", "name": "Guam", "code": "GU" },
  { "id": "_FPgCT6rb0w7twQB", "name": "Guatemala", "code": "GT" },
  { "id": "H2r_XTq_9BAKi96s", "name": "Guernsey", "code": "GG" },
  { "id": "CpD2nfGVJ4u0c4Qw", "name": "Guinea", "code": "GN" },
  { "id": "n7UUi-E2yXBOBQ_V", "name": "Guinea-bissau", "code": "GW" },
  { "id": "KpiczJo5kgaeH0ty", "name": "Guyana", "code": "GY" },
  { "id": "XAAlwgrIQFC_G7GQ", "name": "Haiti", "code": "HT" },
  { "id": "erSGpSryGXmPIFBN", "name": "Heard Island And Mcdonald Islands", "code": "HM" },
  { "id": "T5lC_nDeODdL8Srp", "name": "Holy See (vatican City State)", "code": "VA" },
  { "id": "8Odf0CtMdfGjB1vq", "name": "Honduras", "code": "HN" },
  { "id": "qPaONWNN4esr2duY", "name": "Hong Kong", "code": "HK" },
  { "id": "DJq0_lwiZaGfSKBo", "name": "Hungary", "code": "HU" },
  { "id": "6BA8KwKFvBnBn6si", "name": "Iceland", "code": "IS" },
  { "id": "c3l_NLoXsuiVawWv", "name": "India", "code": "IN" },
  { "id": "B1UdJ0vrO3ZbXRrG", "name": "Indonesia", "code": "ID" },
  { "id": "nE65ekIuOOSodk-0", "name": "Iran, Islamic Republic Of", "code": "IR" },
  { "id": "xUmyloeLi2OxySJ4", "name": "Iraq", "code": "IQ" },
  { "id": "pa5EEoiyoba4K_le", "name": "Ireland", "code": "IE" },
  { "id": "pMytIeRPwi2ZEHv7", "name": "Isle Of Man", "code": "IM" },
  { "id": "L21bn4pI2hn2hGwg", "name": "Israel", "code": "IL" },
  { "id": "okr6_HB7tA1gZVjI", "name": "Italy", "code": "IT" },
  { "id": "2p3WHisnMr-kENq7", "name": "Jamaica", "code": "JM" },
  { "id": "heacFjBdysJ36OTt", "name": "Japan", "code": "JP" },
  { "id": "FUtzpoluHCI2R4DG", "name": "Jersey", "code": "JE" },
  { "id": "L4ey7lpuFfSYZBGF", "name": "Jordan", "code": "JO" },
  { "id": "8zGhdddW1u_pEJWI", "name": "Kazakhstan", "code": "KZ" },
  { "id": "pZneJlXgo9q9xZej", "name": "Kenya", "code": "KE" },
  { "id": "EnoI03-V44Dke1EE", "name": "Kiribati", "code": "KI" },
  { "id": "enmPI_pRb9Uwh6dU", "name": "Korea, Democratic People s Republic Of", "code": "KP" },
  { "id": "Ewc9oJJ6cA0Tlpe_", "name": "Korea, Republic Of", "code": "KR" },
  { "id": "ZOOy8ULpICiyeIdz", "name": "Kuwait", "code": "KW" },
  { "id": "x-_eRbmB9cscR_4-", "name": "Kyrgyzstan", "code": "KG" },
  { "id": "Tk9Cmy9lZMsjw3Bc", "name": "Lao People Democratic Republic", "code": "LA" },
  { "id": "hH1TgAFefbTf7lfx", "name": "Latvia", "code": "LV" },
  { "id": "jYyP26cbjeI5QHpN", "name": "Lebanon", "code": "LB" },
  { "id": "yHOgKDG7PS8WprVT", "name": "Lesotho", "code": "LS" },
  { "id": "1MU0y-lrQMYiVEP8", "name": "Liberia", "code": "LR" },
  { "id": "ShOr_YXH6zqBFkkc", "name": "Libya", "code": "LY" },
  { "id": "GHUFERyXkleI-low", "name": "Liechtenstein", "code": "LI" },
  { "id": "1FsjtObsznRevMKE", "name": "Lithuania", "code": "LT" },
  { "id": "X3waNrFQJQj9YznH", "name": "Luxembourg", "code": "LU" },
  { "id": "fxuJXz07HCNAeMAi", "name": "Macao", "code": "MO" },
  { "id": "mBpGaqQP_n5p_B3G", "name": "Macedonia, The Former Yugoslav Republic Of", "code": "MK" },
  { "id": "alr-FsHytyvAJxud", "name": "Madagascar", "code": "MG" },
  { "id": "ml4HYyR-IiqLO6Dm", "name": "Malawi", "code": "MW" },
  { "id": "ycr5X7bDiH8Dhn7Z", "name": "Malaysia", "code": "MY" },
  { "id": "qmFcx0JZNPg0DoWp", "name": "Maldives", "code": "MV" },
  { "id": "npcGVO1mV5v4ChO7", "name": "Mali", "code": "ML" },
  { "id": "lfCnuw6FEIAJKeVY", "name": "Malta", "code": "MT" },
  { "id": "rpRGp-R4t2FjtwqA", "name": "Marshall Islands", "code": "MH" },
  { "id": "7uhclLcOdVfXx6ph", "name": "Martinique", "code": "MQ" },
  { "id": "qrCgmo89y8hAud3B", "name": "Mauritania", "code": "MR" },
  { "id": "C7M0sa9NghHGz3_A", "name": "Mauritius", "code": "MU" },
  { "id": "mTwT44YE3tmirniJ", "name": "Mayotte", "code": "YT" },
  { "id": "O139-tc2gFpi4fMu", "name": "Mexico", "code": "MX" },
  { "id": "tCwE2zupwALOSNTp", "name": "Micronesia, Federated States Of", "code": "FM" },
  { "id": "2ETvFrk7Yl-50c8m", "name": "Moldova, Republic Of", "code": "MD" },
  { "id": "PS6FZiAWsV5T94VY", "name": "Monaco", "code": "MC" },
  { "id": "ZVN0gOuutH_0_2T9", "name": "Mongolia", "code": "MN" },
  { "id": "xaswe06CerJBPycm", "name": "Montenegro", "code": "ME" },
  { "id": "_lKkjF6hVluczvj7", "name": "Montserrat", "code": "MS" },
  { "id": "OPYs-nfPI66Lrp4t", "name": "Morocco", "code": "MA" },
  { "id": "9HPzE8jyq2NuTO2Y", "name": "Mozambique", "code": "MZ" },
  { "id": "IBhu5bWiGo-WdcqM", "name": "Myanmar", "code": "MM" },
  { "id": "ZeBDLRQzbKbkiJ3A", "name": "Namibia", "code": "NA" },
  { "id": "cPahplm-ttOOwdNC", "name": "Nauru", "code": "NR" },
  { "id": "et-3B_r2CSkp-SZ8", "name": "Nepal", "code": "NP" },
  { "id": "XjmM-DkUsKfQrtaV", "name": "Netherlands", "code": "NL" },
  { "id": "OXYNGXWiWMpabqOn", "name": "New Caledonia", "code": "NC" },
  { "id": "l-B9DC-82BZf_Qhk", "name": "New Zealand", "code": "NZ" },
  { "id": "ELGiQoosdVWnlpKC", "name": "Nicaragua", "code": "NI" },
  { "id": "6332oIu4PZlE4i_N", "name": "Niger", "code": "NE" },
  { "id": "Q_VjVpwaBRNRjb2F", "name": "Nigeria", "code": "NG" },
  { "id": "beAM5_AK9-RxP9jR", "name": "Niue", "code": "NU" },
  { "id": "b3GGvtVhKJdFytsq", "name": "Norfolk Island", "code": "NF" },
  { "id": "zF0lxvz-8oE3gHuC", "name": "Northern Mariana Islands", "code": "MP" },
  { "id": "8JMIjvVvIRa7rxpx", "name": "Norway", "code": "NO" },
  { "id": "qwWaYKTa3wFHnqlb", "name": "Oman", "code": "OM" },
  { "id": "uYihoMfeqDQ4637o", "name": "Pakistan", "code": "PK" },
  { "id": "Yxv6goJKI2PbwG6x", "name": "Palau", "code": "PW" },
  { "id": "CZLcUuarcFZD-Mxt", "name": "Palestine, State Of", "code": "PS" },
  { "id": "kV-W7Tu2vkZk4ghV", "name": "Panama", "code": "PA" },
  { "id": "LFIMRaIKmL6gD_w5", "name": "Papua New Guinea", "code": "PG" },
  { "id": "4ZE6arFXrJoNdpYR", "name": "Paraguay", "code": "PY" },
  { "id": "29wIi_ODgp-n7kxi", "name": "Peru", "code": "PE" },
  { "id": "82341coaHfgBzEZp", "name": "Philippines", "code": "PH" },
  { "id": "VkqKhKOqvDz9-Fwu", "name": "Pitcairn", "code": "PN" },
  { "id": "oI0Wc7qXhFS_mHyE", "name": "Poland", "code": "PL" },
  { "id": "q2ApFFn51gtLW1z5", "name": "Portugal", "code": "PT" },
  { "id": "wQp-UpmLrjyN-q_y", "name": "Puerto Rico", "code": "PR" },
  { "id": "CzIJ9TbtE_dIFn-Y", "name": "Qatar", "code": "QA" },
  { "id": "mrEVf7aVn0N2DjD2", "name": "Réunion", "code": "RE" },
  { "id": "RO2ErzVgUyvJ7t8q", "name": "Romania", "code": "RO" },
  { "id": "MiNH2jaIK7UTmr11", "name": "Russian Federation", "code": "RU" },
  { "id": "Be05CBUUDyqHpnnO", "name": "Rwanda", "code": "RW" },
  { "id": "UYVEznNq6n4uIcZe", "name": "Saint Barthélemy", "code": "BL" },
  { "id": "FNqUn0OWilkPOzU8", "name": "Saint Helena, Ascension And Tristan Da Cunha", "code": "SH" },
  { "id": "jX-Twu8WA_sv8MRa", "name": "Saint Kitts And Nevis", "code": "KN" },
  { "id": "BpUAUi3fd8tj92ic", "name": "Saint Lucia", "code": "LC" },
  { "id": "2BSJmONFGulQ73sa", "name": "Saint Martin (french Part)", "code": "MF" },
  { "id": "w-yGzRc8POxoVZB0", "name": "Saint Pierre And Miquelon", "code": "PM" },
  { "id": "ArmgzcY_A931UW06", "name": "Saint Vincent And The Grenadines", "code": "VC" },
  { "id": "bcXFtiHiTJyPSt9K", "name": "Samoa", "code": "WS" },
  { "id": "r0CCsOJWFQSrUZzf", "name": "San Marino", "code": "SM" },
  { "id": "tPO58uNuP1TBt_zS", "name": "Sao Tome And Principe", "code": "ST" },
  { "id": "HAU4WAepX6adk_nm", "name": "Saudi Arabia", "code": "SA" },
  { "id": "nB0uwQEDUQtJ383W", "name": "Senegal", "code": "SN" },
  { "id": "EGAJPCTdc9TvK_XM", "name": "Serbia", "code": "RS" },
  { "id": "wcABrMua1c4Apvqq", "name": "Seychelles", "code": "SC" },
  { "id": "8zT_CCRsFa_6Joci", "name": "Sierra Leone", "code": "SL" },
  { "id": "jaN_oyDdvxTHA8AL", "name": "Singapore", "code": "SG" },
  { "id": "vJnfRO1RxhxS3_vK", "name": "Sint Maarten (dutch Part)", "code": "SX" },
  { "id": "mUFjxFeCZfQVF5s0", "name": "Slovakia", "code": "SK" },
  { "id": "PVQgRMLYLLdhA4hA", "name": "Slovenia", "code": "SI" },
  { "id": "dR0Z6o0TF8cQWF05", "name": "Solomon Islands", "code": "SB" },
  { "id": "eSOeVzaLFXt9F97r", "name": "Somalia", "code": "SO" },
  { "id": "g4NMuEOyfooJcDSn", "name": "South Africa", "code": "ZA" },
  { "id": "ysTOQQYWdd9kFSYg", "name": "South Georgia And The South Sandwich Islands", "code": "GS" },
  { "id": "Aro85Z2HejcQq4Zw", "name": "South Sudan", "code": "SS" },
  { "id": "KwdIx3DsNhoEHynE", "name": "Spain", "code": "ES" },
  { "id": "Xhwb2iSmm6f73Lk1", "name": "Sri Lanka", "code": "LK" },
  { "id": "IdsgmwOhe1kbsP-Z", "name": "Sudan", "code": "SD" },
  { "id": "_q2z0k6uu-SzgUVc", "name": "Suriname", "code": "SR" },
  { "id": "uEBr4HgXKFZ6dIX9", "name": "Svalbard And Jan Mayen", "code": "SJ" },
  { "id": "nN_ifJraHwjsIAne", "name": "Swaziland", "code": "SZ" },
  { "id": "t3t5QsB2JERRZfen", "name": "Sweden", "code": "SE" },
  { "id": "kJV2NHQ2a0S3CrAH", "name": "Switzerland", "code": "CH" },
  { "id": "mZB1DxhXkrlbluYs", "name": "Syrian Arab Republic", "code": "SY" },
  { "id": "FX6C6a_kdZqSm4Eh", "name": "Taiwan", "code": "TW" },
  { "id": "0W_qOYUcdI88kiGT", "name": "Tajikistan", "code": "TJ" },
  { "id": "IVu926qR5Xc1-ccn", "name": "Tanzania, United Republic Of", "code": "TZ" },
  { "id": "VCNeSv2VSaxdYnzb", "name": "Thailand", "code": "TH" },
  { "id": "4Ybs91TfdfT5pKdh", "name": "Timor-leste", "code": "TL" },
  { "id": "jefYI907W3ZR5MND", "name": "Togo", "code": "TG" },
  { "id": "IKu8cL1UG2BpJ7MK", "name": "Tokelau", "code": "TK" },
  { "id": "hkGSVOEvcCxODMze", "name": "Tonga", "code": "TO" },
  { "id": "E9vAOhPxOSSxpHPL", "name": "Trinidad And Tobago", "code": "TT" },
  { "id": "aQDt0J9nDPOZiARQ", "name": "Tunisia", "code": "TN" },
  { "id": "lGSNBD54BICttyG8", "name": "Turkey", "code": "TR" },
  { "id": "xnic6iHPMbXTyfUz", "name": "Turkmenistan", "code": "TM" },
  { "id": "w3tlwNlUWZfMJ63w", "name": "Turks And Caicos Islands", "code": "TC" },
  { "id": "5NcRejxK0ZKhZzGO", "name": "Tuvalu", "code": "TV" },
  { "id": "f-75M1Tli49xsnMT", "name": "Uganda", "code": "UG" },
  { "id": "C57E1KHoi-konMfF", "name": "Ukraine", "code": "UA" },
  { "id": "mtgEY_-OhvTBShl9", "name": "United Arab Emirates", "code": "AE" },
  { "id": "GchktFD95-9Rl7KR", "name": "United Kingdom", "code": "GB" },
  { "id": "fc5Gr4K6SjWsMeux", "name": "United States", "code": "US" },
  { "id": "PEpInywaT2Oh6M2J", "name": "United States Minor Outlying Islands", "code": "UM" },
  { "id": "R5cX_6bU6pflh0FF", "name": "Uruguay", "code": "UY" },
  { "id": "EY2Z2XGQumSDFB1P", "name": "Uzbekistan", "code": "UZ" },
  { "id": "Yy9QV_cP8x-EhXne", "name": "Vanuatu", "code": "VU" },
  { "id": "puX2VBT880w3xGbm", "name": "Venezuela, Bolivarian Republic Of", "code": "VE" },
  { "id": "HSVMSL4CjWglRJ2s", "name": "Viet Nam", "code": "VN" },
  { "id": "SBjdYoYp-r767cMI", "name": "Virgin Islands, British", "code": "VG" },
  { "id": "XmezGSTFLKIURPuR", "name": "Virgin Islands, U.s.", "code": "VI" },
  { "id": "-KvFaE3hSsqnJF63", "name": "Wallis And Futuna", "code": "WF" },
  { "id": "33kNIWTaneNUkBdx", "name": "Western Sahara", "code": "EH" },
  { "id": "YDt6pf76ldhOcWSB", "name": "Kosovo", "code": "KV" },
  { "id": "RQnngXkCRuBcCZYw", "name": "Yemen", "code": "YE" },
  { "id": "RQs-wBXDVlsGmaq8", "name": "Zambia", "code": "ZM" },
  { "id": "l3pKu8YaidtQ_Psa", "name": "Zimbabwe", "code": "ZW" }
];

